[package]
name = "electrumx_client"
version = "0.2.0"
authors = ["evgeniy.scherbina <evgeniy.scherbina@bitfury.com>"]

[dependencies]
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
bitcoin = "0.26.0"
hex = "0.3.2"
sha2 = "0.8.0"
clap = "2.32.0"
rust_decimal = "1"
